title: Titel van mijn pagina
author: Petra
email: kiwimaori2001@yahoo.co.nz
description: > # this means to ignore newlines until "baseurl:"
 omschrijving van deze pagina
# social links
twitter_username: pmastenbroek # DO NOT include the @ character, or else the build will fail!
github_username:  petra # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
